[2022-08-17 20:42:57,104] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T20:17:49.248045+00:00 [queued]>
[2022-08-17 20:42:57,112] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T20:17:49.248045+00:00 [queued]>
[2022-08-17 20:42:57,112] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:42:57,113] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2022-08-17 20:42:57,113] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:42:57,126] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 20:17:49.248045+00:00
[2022-08-17 20:42:57,130] {standard_task_runner.py:52} INFO - Started process 4321 to run task
[2022-08-17 20:42:57,133] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T20:17:49.248045+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpu_7e6fkp', '--error-file', '/tmp/tmpxg3x4z06']
[2022-08-17 20:42:57,134] {standard_task_runner.py:80} INFO - Job 110: Subtask extract
[2022-08-17 20:42:57,189] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T20:17:49.248045+00:00 [running]> on host 8c93e37464e5
[2022-08-17 20:42:57,253] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T20:17:49.248045+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T20:17:49.248045+00:00
[2022-08-17 20:42:57,260] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 76, in extractData
    files = os.listdir(dir_name)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Unitronics Data Logs/'
[2022-08-17 20:42:57,271] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T201749, start_date=20220817T204257, end_date=20220817T204257
[2022-08-17 20:42:57,282] {standard_task_runner.py:97} ERROR - Failed to execute job 110 for task extract ([Errno 2] No such file or directory: 'C:/Unitronics Data Logs/'; 4321)
[2022-08-17 20:42:57,305] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 20:42:57,342] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
