[2022-08-18 19:46:25,903] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-18T13:16:08.458865+00:00 [queued]>
[2022-08-18 19:46:25,913] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-18T13:16:08.458865+00:00 [queued]>
[2022-08-18 19:46:25,913] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 19:46:25,914] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-18 19:46:25,914] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 19:46:25,930] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-18 13:16:08.458865+00:00
[2022-08-18 19:46:25,934] {standard_task_runner.py:52} INFO - Started process 178 to run task
[2022-08-18 19:46:25,940] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-18T13:16:08.458865+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpzenc9nrt', '--error-file', '/tmp/tmpgt3hisoy']
[2022-08-18 19:46:25,941] {standard_task_runner.py:80} INFO - Job 69: Subtask extract
[2022-08-18 19:46:26,000] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-18T13:16:08.458865+00:00 [running]> on host 1b0f89009e2c
[2022-08-18 19:46:26,079] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T13:16:08.458865+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T13:16:08.458865+00:00
[2022-08-18 19:46:26,085] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 76, in extractData
    files = os.listdir(dir_name)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/cavefish1/Unitronics_Data_Logs'
[2022-08-18 19:46:26,095] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220818T131608, start_date=20220818T194625, end_date=20220818T194626
[2022-08-18 19:46:26,108] {standard_task_runner.py:97} ERROR - Failed to execute job 69 for task extract ([Errno 2] No such file or directory: 'C:/Users/cavefish1/Unitronics_Data_Logs'; 178)
[2022-08-18 19:46:26,148] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 19:46:26,199] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
