[2022-08-17 19:34:42,179] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:29:39.490076+00:00 [queued]>
[2022-08-17 19:34:42,189] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:29:39.490076+00:00 [queued]>
[2022-08-17 19:34:42,190] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:34:42,190] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-17 19:34:42,190] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:34:42,205] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:29:39.490076+00:00
[2022-08-17 19:34:42,209] {standard_task_runner.py:52} INFO - Started process 538 to run task
[2022-08-17 19:34:42,217] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:29:39.490076+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmp5g_s45t7', '--error-file', '/tmp/tmpprekhnzq']
[2022-08-17 19:34:42,219] {standard_task_runner.py:80} INFO - Job 11: Subtask extract
[2022-08-17 19:34:42,289] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:29:39.490076+00:00 [running]> on host 2ea01d049be8
[2022-08-17 19:34:42,366] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:29:39.490076+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:29:39.490076+00:00
[2022-08-17 19:34:42,375] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 94, in extractData
    device_df = concatDataFrame(super_df_device)
  File "/opt/airflow/dags/unitronics_ETL.py", line 53, in concatDataFrame
    df = pd.concat(df, axis=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2022-08-17 19:34:42,389] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T192939, start_date=20220817T193442, end_date=20220817T193442
[2022-08-17 19:34:42,403] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task extract (No objects to concatenate; 538)
[2022-08-17 19:34:42,427] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:34:42,478] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
