[2022-08-17 18:54:31,334] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T18:54:29.717453+00:00 [queued]>
[2022-08-17 18:54:31,347] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T18:54:29.717453+00:00 [queued]>
[2022-08-17 18:54:31,348] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:54:31,348] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 18:54:31,349] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:54:31,363] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 18:54:29.717453+00:00
[2022-08-17 18:54:31,367] {standard_task_runner.py:52} INFO - Started process 776 to run task
[2022-08-17 18:54:31,371] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T18:54:29.717453+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmp4zee089i', '--error-file', '/tmp/tmpiu4esita']
[2022-08-17 18:54:31,372] {standard_task_runner.py:80} INFO - Job 3: Subtask extract
[2022-08-17 18:54:31,448] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T18:54:29.717453+00:00 [running]> on host a9aa2b837f24
[2022-08-17 18:54:31,544] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T18:54:29.717453+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T18:54:29.717453+00:00
[2022-08-17 18:54:31,545] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extractData() missing 1 required positional argument: 'dir_name'
[2022-08-17 18:54:31,553] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T185429, start_date=20220817T185431, end_date=20220817T185431
[2022-08-17 18:54:31,565] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task extract (extractData() missing 1 required positional argument: 'dir_name'; 776)
[2022-08-17 18:54:31,585] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 18:54:31,631] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
