[2022-08-17 13:09:24,190] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-16T00:00:00+00:00 [queued]>
[2022-08-17 13:09:24,200] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-16T00:00:00+00:00 [queued]>
[2022-08-17 13:09:24,201] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 13:09:24,202] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 13:09:24,203] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 13:09:24,219] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-16 00:00:00+00:00
[2022-08-17 13:09:24,225] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2022-08-17 13:09:24,230] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'scheduled__2022-08-16T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpm2ry8tf3', '--error-file', '/tmp/tmpxflh833v']
[2022-08-17 13:09:24,234] {standard_task_runner.py:80} INFO - Job 23: Subtask extract
[2022-08-17 13:09:24,290] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-16T00:00:00+00:00 [running]> on host 34b373f0486d
[2022-08-17 13:09:24,361] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-16T00:00:00+00:00
[2022-08-17 13:09:24,363] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extractData() missing 1 required positional argument: 'dir_name'
[2022-08-17 13:09:24,373] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220816T000000, start_date=20220817T130924, end_date=20220817T130924
[2022-08-17 13:09:24,387] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task extract (extractData() missing 1 required positional argument: 'dir_name'; 173)
[2022-08-17 13:09:24,400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 13:09:24,438] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
