[2022-08-15 00:15:05,162] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2022-08-15 00:15:05,170] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2022-08-15 00:15:05,171] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 00:15:05,172] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2022-08-15 00:15:05,172] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 00:15:05,187] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-14 00:00:00+00:00
[2022-08-15 00:15:05,192] {standard_task_runner.py:52} INFO - Started process 13893 to run task
[2022-08-15 00:15:05,195] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'scheduled__2022-08-14T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpz7nby3p1', '--error-file', '/tmp/tmpwow_p4n2']
[2022-08-15 00:15:05,196] {standard_task_runner.py:80} INFO - Job 8: Subtask extract
[2022-08-15 00:15:05,251] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [running]> on host 34b373f0486d
[2022-08-15 00:15:05,313] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-14T00:00:00+00:00
[2022-08-15 00:15:05,315] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extractData() missing 1 required positional argument: 'dir_name'
[2022-08-15 00:15:05,323] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220814T000000, start_date=20220815T001505, end_date=20220815T001505
[2022-08-15 00:15:05,334] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task extract (extractData() missing 1 required positional argument: 'dir_name'; 13893)
[2022-08-15 00:15:05,368] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-15 00:15:05,408] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
