[2022-08-15 00:05:03,130] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2022-08-15 00:05:03,139] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [queued]>
[2022-08-15 00:05:03,139] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 00:05:03,140] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-15 00:05:03,141] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 00:05:03,154] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-14 00:00:00+00:00
[2022-08-15 00:05:03,158] {standard_task_runner.py:52} INFO - Started process 13288 to run task
[2022-08-15 00:05:03,161] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'scheduled__2022-08-14T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmps07lrrkj', '--error-file', '/tmp/tmpff09kznl']
[2022-08-15 00:05:03,162] {standard_task_runner.py:80} INFO - Job 6: Subtask extract
[2022-08-15 00:05:03,214] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract scheduled__2022-08-14T00:00:00+00:00 [running]> on host 34b373f0486d
[2022-08-15 00:05:03,273] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-14T00:00:00+00:00
[2022-08-15 00:05:03,275] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extractData() missing 1 required positional argument: 'dir_name'
[2022-08-15 00:05:03,282] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220814T000000, start_date=20220815T000503, end_date=20220815T000503
[2022-08-15 00:05:03,291] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task extract (extractData() missing 1 required positional argument: 'dir_name'; 13288)
[2022-08-15 00:05:03,333] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-15 00:05:03,372] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
