[2022-08-17 19:19:22,036] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:19:21.283691+00:00 [queued]>
[2022-08-17 19:19:22,046] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:19:21.283691+00:00 [queued]>
[2022-08-17 19:19:22,047] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:19:22,048] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 19:19:22,048] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:19:22,061] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:19:21.283691+00:00
[2022-08-17 19:19:22,066] {standard_task_runner.py:52} INFO - Started process 1315 to run task
[2022-08-17 19:19:22,069] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:19:21.283691+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpcvdhvl17', '--error-file', '/tmp/tmpe7970f09']
[2022-08-17 19:19:22,070] {standard_task_runner.py:80} INFO - Job 22: Subtask extract
[2022-08-17 19:19:22,133] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:19:21.283691+00:00 [running]> on host ea4c9b9e2e97
[2022-08-17 19:19:22,205] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:19:21.283691+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:19:21.283691+00:00
[2022-08-17 19:19:22,214] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 95, in extractData
    device_df = concatDataFrame(super_df_device)
  File "/opt/airflow/dags/unitronics_ETL.py", line 54, in concatDataFrame
    df = pd.concat(df, axis=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2022-08-17 19:19:22,225] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T191921, start_date=20220817T191922, end_date=20220817T191922
[2022-08-17 19:19:22,236] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task extract (No objects to concatenate; 1315)
[2022-08-17 19:19:22,281] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:19:22,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
