[2022-08-17 20:04:59,441] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:59:57.400711+00:00 [queued]>
[2022-08-17 20:04:59,449] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:59:57.400711+00:00 [queued]>
[2022-08-17 20:04:59,450] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:04:59,450] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-17 20:04:59,451] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:04:59,463] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:59:57.400711+00:00
[2022-08-17 20:04:59,466] {standard_task_runner.py:52} INFO - Started process 1862 to run task
[2022-08-17 20:04:59,469] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:59:57.400711+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpy83t8oih', '--error-file', '/tmp/tmpyuwhqo49']
[2022-08-17 20:04:59,470] {standard_task_runner.py:80} INFO - Job 53: Subtask extract
[2022-08-17 20:04:59,522] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:59:57.400711+00:00 [running]> on host 8c93e37464e5
[2022-08-17 20:04:59,585] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:59:57.400711+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:59:57.400711+00:00
[2022-08-17 20:04:59,591] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 75, in extractData
    files = os.listdir(dir_name)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Unitronics Data Logs/'
[2022-08-17 20:04:59,601] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T195957, start_date=20220817T200459, end_date=20220817T200459
[2022-08-17 20:04:59,614] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task extract ([Errno 2] No such file or directory: 'C:/Unitronics Data Logs/'; 1862)
[2022-08-17 20:04:59,641] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 20:04:59,678] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
