[2022-08-17 19:44:41,562] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.transform manual__2022-08-17T19:44:39.321642+00:00 [queued]>
[2022-08-17 19:44:41,573] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.transform manual__2022-08-17T19:44:39.321642+00:00 [queued]>
[2022-08-17 19:44:41,573] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:44:41,574] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 19:44:41,574] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:44:41,589] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform> on 2022-08-17 19:44:39.321642+00:00
[2022-08-17 19:44:41,593] {standard_task_runner.py:52} INFO - Started process 493 to run task
[2022-08-17 19:44:41,596] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'transform', 'manual__2022-08-17T19:44:39.321642+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmp6105ng2m', '--error-file', '/tmp/tmpetb27hv6']
[2022-08-17 19:44:41,597] {standard_task_runner.py:80} INFO - Job 9: Subtask transform
[2022-08-17 19:44:41,667] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.transform manual__2022-08-17T19:44:39.321642+00:00 [running]> on host 8c93e37464e5
[2022-08-17 19:44:41,740] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:44:39.321642+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:44:39.321642+00:00
[2022-08-17 19:44:41,742] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transformData() missing 3 required positional arguments: 'device_df', 'sensor_df', and 'alarm_df'
[2022-08-17 19:44:41,749] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=transform, execution_date=20220817T194439, start_date=20220817T194441, end_date=20220817T194441
[2022-08-17 19:44:41,759] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task transform (transformData() missing 3 required positional arguments: 'device_df', 'sensor_df', and 'alarm_df'; 493)
[2022-08-17 19:44:41,768] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:44:41,810] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
