[2022-08-17 19:02:12,599] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:02:11.307950+00:00 [queued]>
[2022-08-17 19:02:12,610] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:02:11.307950+00:00 [queued]>
[2022-08-17 19:02:12,611] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:02:12,612] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 19:02:12,612] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:02:12,638] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:02:11.307950+00:00
[2022-08-17 19:02:12,642] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-08-17 19:02:12,647] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:02:11.307950+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmputm88bxa', '--error-file', '/tmp/tmpki_veqgo']
[2022-08-17 19:02:12,649] {standard_task_runner.py:80} INFO - Job 4: Subtask extract
[2022-08-17 19:02:12,726] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:02:11.307950+00:00 [running]> on host ea4c9b9e2e97
[2022-08-17 19:02:12,810] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:02:11.307950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:02:11.307950+00:00
[2022-08-17 19:02:12,811] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extractData() missing 1 required positional argument: 'dir_name'
[2022-08-17 19:02:12,820] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T190211, start_date=20220817T190212, end_date=20220817T190212
[2022-08-17 19:02:12,834] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task extract (extractData() missing 1 required positional argument: 'dir_name'; 225)
[2022-08-17 19:02:12,862] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:02:12,929] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
