[2022-08-17 19:10:16,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:05:14.180302+00:00 [queued]>
[2022-08-17 19:10:16,648] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:05:14.180302+00:00 [queued]>
[2022-08-17 19:10:16,648] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:10:16,649] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-17 19:10:16,649] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:10:16,664] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:05:14.180302+00:00
[2022-08-17 19:10:16,667] {standard_task_runner.py:52} INFO - Started process 740 to run task
[2022-08-17 19:10:16,669] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:05:14.180302+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmptvu2s1xv', '--error-file', '/tmp/tmp_d28tgsz']
[2022-08-17 19:10:16,670] {standard_task_runner.py:80} INFO - Job 12: Subtask extract
[2022-08-17 19:10:16,725] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:05:14.180302+00:00 [running]> on host ea4c9b9e2e97
[2022-08-17 19:10:16,791] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:05:14.180302+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:05:14.180302+00:00
[2022-08-17 19:10:16,798] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 95, in extractData
    device_df = concatDataFrame(super_df_device)
  File "/opt/airflow/dags/unitronics_ETL.py", line 54, in concatDataFrame
    df = pd.concat(df, axis=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2022-08-17 19:10:16,809] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T190514, start_date=20220817T191016, end_date=20220817T191016
[2022-08-17 19:10:16,821] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task extract (No objects to concatenate; 740)
[2022-08-17 19:10:16,842] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:10:16,879] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
