[2022-08-17 19:43:07,179] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [queued]>
[2022-08-17 19:43:07,188] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [queued]>
[2022-08-17 19:43:07,188] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:43:07,189] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-17 19:43:07,189] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:43:07,206] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:43:05.926255+00:00
[2022-08-17 19:43:07,210] {standard_task_runner.py:52} INFO - Started process 387 to run task
[2022-08-17 19:43:07,214] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:43:05.926255+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmpwwk2s7gt', '--error-file', '/tmp/tmpty41slu_']
[2022-08-17 19:43:07,215] {standard_task_runner.py:80} INFO - Job 7: Subtask extract
[2022-08-17 19:43:07,284] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [running]> on host 8c93e37464e5
[2022-08-17 19:43:07,368] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:43:05.926255+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:43:05.926255+00:00
[2022-08-17 19:43:07,374] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 112, in extractData
    return rack_number
UnboundLocalError: local variable 'rack_number' referenced before assignment
[2022-08-17 19:43:07,387] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T194305, start_date=20220817T194307, end_date=20220817T194307
[2022-08-17 19:43:07,400] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task extract (local variable 'rack_number' referenced before assignment; 387)
[2022-08-17 19:43:07,427] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:43:07,480] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
