[2022-08-17 19:48:08,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [queued]>
[2022-08-17 19:48:08,649] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [queued]>
[2022-08-17 19:48:08,650] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:48:08,650] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-08-17 19:48:08,651] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:48:08,664] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2022-08-17 19:43:05.926255+00:00
[2022-08-17 19:48:08,668] {standard_task_runner.py:52} INFO - Started process 724 to run task
[2022-08-17 19:48:08,671] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'unitronics_ETL_v01', 'extract', 'manual__2022-08-17T19:43:05.926255+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/unitronics_ETL.py', '--cfg-path', '/tmp/tmp46m274w_', '--error-file', '/tmp/tmpe28jct5q']
[2022-08-17 19:48:08,672] {standard_task_runner.py:80} INFO - Job 15: Subtask extract
[2022-08-17 19:48:08,731] {task_command.py:371} INFO - Running <TaskInstance: unitronics_ETL_v01.extract manual__2022-08-17T19:43:05.926255+00:00 [running]> on host 8c93e37464e5
[2022-08-17 19:48:08,810] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Cavefish
AIRFLOW_CTX_DAG_ID=unitronics_ETL_v01
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:43:05.926255+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:43:05.926255+00:00
[2022-08-17 19:48:08,818] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/unitronics_ETL.py", line 75, in extractData
    root, dirs, files = os.walk(dir_name)
ValueError: not enough values to unpack (expected 3, got 0)
[2022-08-17 19:48:08,829] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=unitronics_ETL_v01, task_id=extract, execution_date=20220817T194305, start_date=20220817T194808, end_date=20220817T194808
[2022-08-17 19:48:08,841] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task extract (not enough values to unpack (expected 3, got 0); 724)
[2022-08-17 19:48:08,882] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 19:48:08,925] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
